### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by lgagne413** [deschman/reporting#1]
Could we make some dependencies optional?  I'm having trouble with fastparquet and pytest_dbfixtures.  Generally speaking I think less is more when it comes to imports in general.

**Comment by deschman** [comment]
Agreed. I have been experiencing a similar issue and have patched this in master with a temporary fix. Dependencies should definitely be revisited before publishing to create a longer-term solution.

**Comment by lgagne413** [comment]
I reccommend the parameter default for bolMulti in SimpleReport.run be False.  In the future we could add functionality to switch to single thread if multi thread fails - multi threading does not seem to work on my server, the queries seem to get in each others way.

**Comment by deschman** [comment]
Optional dependencies should be active in version 0.3.0, #4 . If problems persist, I can re-open.
